apiVersion: v1
kind: Pod
metadata:
  labels:
    name: postgres-pod
    app: demo-voting-app
  name: postgres-pod
spec:
  containers:
    - name: postgeres
      image: postgres:9.4
      ports:
        - containerPort: 5432