apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-pod
    app: demo-voting-app
  name: redis-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379