apiVersion: v1
kind: Pod
metadata:
  labels:
    name: result-app-pod
    app: demo-voting-app
  name: result-app-pod
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
      