apiVersion: v1
kind: Pod
metadata:
  labels:
    name: worker-app-pod
    app: demo-voting-app
  name: worker-app-pod
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
